import pytest

from pyblast.serializer import _serialize_data, parse_results
from pyblast.pysequence import PySequence


@pytest.fixture(scope="module")
def example_raw_results(HERE):
    return HERE


import os


class TestSerializer:
    raw_data = {'query acc.': 'Query_1', 'subject acc.': '756c05c4-f3f2-4e3b-a344-a4ed75827529', 'score': 4219,
                'evalue': 0, 'bit score': 7792, 'alignment length': 4219, 'identical': 4219, 'gap opens': 0, 'gaps': 0,
                'query length': 10781, 'q. start': 1374, 'q. end': 5592, 'subject length': 7883, 's. start': 1,
                's. end': 4219, 'subject strand': 'plus',
                'query seq': 'AAAAA',
                'subject seq': 'TCGCG', }

    context = {'db': {
        '756c05c4-f3f2-4e3b-a344-a4ed75827529': PySequence('', '', 'myseq', '', None, [], {}, {}, filename='myfilename',
                                                           circular=True)
    }}

    serialized = _serialize_data([raw_data], context)
    expected = {
        'query': {
            'query acc.': 'Query_1',
            'query length': 10781,
            'q. start': 1374, 'q. end': 5592,
            'circular': None,
            'name': None,
            'query seq': 'AAAAA',
        },
        'subject': {
            'subject acc.': '756c05c4-f3f2-4e3b-a344-a4ed75827529',
            'subject length': 7883,
            's. start': 1,
            's. end': 4219,
            'subject strand': 'plus',
            'circular': True,
            'name': 'myseq',
            'subject seq': 'TCGCG'
        },
        'meta': {
            'score': 4219, 'evalue': 0,
            'bit score': 7792, 'alignment length': 4219,
            'identical': 4219, 'gap opens': 0, 'gaps': 0
        }
    }

    def test_serializes_subject(self):
        assert TestSerializer.expected['subject'] == TestSerializer.serialized[0]['subject']

    def test_serializes_query(self):
        assert TestSerializer.expected['query'] == TestSerializer.serialized[0]['query']

    def test_serializes_meta(self):
        assert TestSerializer.expected['meta'] == TestSerializer.serialized[0]['meta']


def test_parser(here):
    path = os.path.join(here, 'data/example_raw_blast_results')
    with open(path, 'r') as f:
        data = f.read()

    parsed = parse_results(data, ',')
    expected_first = {
        'subject': {'length': 7883, 'strand': 'plus', 'end': 4219, 'circular': None,
                    'acc': '475e3b13-8206-4a7f-83ba-126c3fd9b7d4', 'start': 1, 'name': None,
                    'sequence': 'TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGACGGTCACAGCTTGTCTGTAAGCGGATGCCGGGAGCAGACAAGCCCGTCAGGGCGCGTCAGCGGGTGTTGGCGGGTGTCGGGGCTGGCTTAACTATGCGGCGTTTAAACTTAGCAGATGCGCGCACCTGCGTTGTTACCACAACTCTTATGAGGCCCGCGGACAGCATCAAACTGTAAGATTCCGCCACATTTTATACACTCTGGTCCTTTAACTGGCAAACCTTCGGGCGTAATGCCCAATTTTTCGCCTTTGTCTTTTGCCTTTTTCACTTCACGTGCTTCTGGTACATACTTGCAATTTATACAGTGATGACCGCTGAATTTGTATCTTCCATAGCATCTAGCACATACTCGATTTTTACCACTCCAATCTTTATAAAAATACTTGATTCCCTTTCTGGGACAAGCAACACAGTGTTTTAGATTCTTTTTTTGTGATATTTTAAGCTGTTCTCCCACACAGCAGCCTCGACATGATTTCACTTCTATTTTGTTGCCAAGCAAGAAATTTTTATGGCCTTCTATCGTAAGCCCATATACAGTACTCTCACCCTGGAAATCATCCGTGAAGCTGAAATATACGGGTTCCCTTTTTATAATTGGCGGAACTTCTCTTGTTTTGTGACCACTTCGACAATATGACAAAACATTCTGTGAAGTTGTTCCCCCAGCATCAGAGCAGATTGTACTGAGAGTGCACCGGCGCGCCAGATCTGTTTAGCTTGCCTCGTCCCCGCCGGGTCACCCGGCCAGCGACATGGGGGCCCAGAATACCCTCCTTGACAGTCTTGACGTGCGCAGCTCAGGGGCATGATGTGACTGTCGCCCGTACATTTAGCCCATACATCCCCATGTATAATCATTTGCATCCATACATTTTGATGGCCGCACGGCGCGAAGCAAAAATTACGGCTCCTCGCTGCAGACCTGCGAGCAGGGAAACGCTCCCCTCACAGACGCGTTGAATTGTCCCCACGCCGCGCCCCTGTAGAGAAATATAAAAGGTTAGGATTTGCCACTGAGGTTCTTCTTTCATATACTTCCTTTTAAAATCTTGCTAGGATACAGTTCTCACATCACATCCGAACATAAACAACCATGGGTAAGGAAAAGACTCACGTTTCGAGGCCGCGATTAAATTCCAACATGGATGCTGATTTATATGGGTATAAATGGGCTCGCGATAATGTCGGGCAATCAGGTGCGACAATCTATCGATTGTATGGGAAGCCCGATGCGCCAGAGTTGTTTCTGAAACATGGCAAAGGTAGCGTTGCCAATGATGTTACAGATGAGATGGTCAGACTAAACTGGCTGACGGAATTTATGCCTCTTCCGACCATCAAGCATTTTATCCGTACTCCTGATGATGCATGGTTACTCACCACTGCGATCCCCGGCAAAACAGCATTCCAGATATTAGAAGAATATCCTGATTCAGGTGAAAATATTGTTGATGCGCTGGCAGTGTTCCTGCGCCGGTTGCATTCGATTCCTGTTTGTAATTGTCCTTTTAACAGCGATCGCGTATTTCGTCTCGCTCAGGCGCAATCACGAATGAATAACGGTTTGGTTGATGCGAGTGATTTTGATGACGAGCGTAATGGCTGGCCTGTTGAACAAGTCTGGAAAGAAATGCATAAGCTTTTGCCATTCTCACCGGATTCAGTCGTCACTCATGGTGATTTCTCACTTGATAACCTTATTTTTGACGAGGGGAAATTAATAGGTTGTATTGATGTTGGACGAGTCGGAATCGCAGACCGATACCAGGATCTTGCCATCCTATGGAACTGCCTCGGTGAGTTTTCTCCTTCATTACAGAAACGGCTTTTTCAAAAATATGGTATTGATAATCCTGATATGAATAAATTGCAGTTTCATTTGATGCTCGATGAGTTTTTCTAATCAGTACTGACAATAAAAAGATTCTTGTTTTCAAGAACTTGTCATTTGTATAGTTTTTTTATATTGTAGTTGTTCTATTTTAATCAAATGTTAGCGTGATTTATATTTTTTTTCGCCTCGACATCATCTGCCCAGATGCGAAGTTAAGTGCGCAGAAAGTAATATCATGCGTCAATCGTATGTGAATGCTGGTCGCTATACTGCTGTCGATTCGATACTAACGCCGCCATCCAGTGTCCGCCAGGGTTTTCCCAGTCACGACGCCTCTACCTTGCAGACCCATATAATATAATAACTAAATAAGTAAATAAGACACACGCGAGAACATATATACACAATTACAGTAACAATAACAAGAGGACAGATACTACCAAAATGTGTGGGGAAGCGGGTAAGCTGCCACAGCAATTAATGCACAACATTTAACCTACATTCTTCCTTATCGGATCCTCAAAACCCTTAAAAACATATGCCTCACCCTAACATATTTTCCAATTAACCCTCAATATTTCTCTGTCACCCGGCCTCTATTTTCCATTTTCTTCTTTACCCGCCACGCGTTTTTTTCTTTCAAATTTTTTTCTTCCTTCTTCTTTTTCTTCCACGTCCTCTTGCATAAATAAATAAACCGTTTTGAAACCAAACTCGCCTCTCTCTCTCCTTTTTGAAATATTTTTGGGTTTGTTTGATCCTTTCCTTCCCAATCTCTCTTGTTTAATATATATTCATTTATATCACGCTCTCTTTTTATCTTCCTTTTTTTCCTCTCTCTTGTATTCTTCCTTCCCCTTTCTACTCAAACCAAGAAGAAAAAGAAAAGGTCAATCTTTGTTAAAGAATAGGATCTTCTACTACATCAGCTTTTAGATTTTTCACGCTTACTGCTTTTTTCTTCCCAAGATCGAAAATTTACTGAATTAACAGGGCCCCCCCTCGAGGTCGACGGTATCGATAAGCTTGAAGCAAGCCTCCTGAAAGATGGGTACCCGCCCATATGCTTGCCCTGTCGAGTCCTGCGATCGCCGCTTTTCTCGCCACGCCAATCTTACCCGCCATATCCGCATCCATACCGGTCAGAAGCCCTTCCAGTGTCGAATCTGCATGCGTAACTTCAGTCGTAATGCGAACCTTGTGCGCCACATCCGCACCCACACAGGATCCCAAAAGCCGTTCCAATGTCGGATCTGTATGCGGAACTTTAGTCGAAAGGCCGACCTGAGGCGTCACATTCGCACGCACACCGGCGAGAAGCCTTTTGCCTGTGACATTTGTGGGAGGAAGTTTGCCAGGAAGGGCGACCTCAAGAGGCATACCAAAATCCATACAGGTGGCGGAGGCACACCTGCAGCTGCGTCGACTCTAGAGGATCCATCTGCTGGAGACATGAGAGCTGCCAACCTTTGGCCAAGCCCGCTCATGATCAAACGCTCTAAGAAGAACAGCCTGGCCTTGTCCCTGACGGCCGACCAGATGGTCAGTGCCTTGTTGGATGCTGAGCCCCCCATACTCTATTCCGAGTATGATCCTACCAGACCCTTCAGTGAAGCTTCGATGATGGGCTTACTGACCAACCTGGCAGACAGGGAGCTGGTTCACATGATCAACTGGGCGAAGAGGGTGCCAGGCTTTGTGGATTTGACCCTCCATGATCAGGTCCACCTTCTAGAATGTGCCTGGCTAGAGATCCTGATGATTGGTCTCGTCTGGCGCTCCATGGAGCACCCAGTGAAGCTACTGTTTGCTCCTAACTTGCTCTTGGACAGGAACCAGGGAAAATGTGTAGAGGGCATGGTGGAGATCTTCGACATGCTGCTGGCTACATCATCTCGGTTCCGCATGATGAATCTGCAGGGAGAGGAGTTTGTGTGCCTCAAATCTATTATTTTGCTTAATTCTGGAGTGTACACATTTCTGTCCAGCACCCTGAAGTCTCTGGAAGAGAAGGACCATATCCACCGAGTCCTGGACAAGATCACAGACACTTTGATCCACCTGATGGCCAAGGCAGGCCTGACCCTGCAGCAGCAGCACCAGCGGCTGGCCCAGCTCCTCCTCATCCTCTCCCACATCAGGCACATGAGTAACAAAGGCATGGAGCATCTGTACAGCATGAAGTGCAAGAACGTGGTGCCCCTCTATGACCTGCTGCTGGAGATGCTGGACGCCCACCGCCTACATGCGCCCACTAGCCGTGGAGGGGCATCCGTGGAGGAGACGGACCAAAGCCACTTGGCCACTGCGGGCTCTACTTCATCGG'},
        'meta': {'gaps': 0, 'score': 4219.0, 'bit_score': 7792, 'gaps_open': 0, 'identical': 4219, 'evalue': 0.0,
                 'alignment_length': 4219},
        'query': {'length': 10781, 'end': 5592, 'circular': None, 'acc': 'Query_1', 'start': 1374,
                  'name': None,
                  'sequence': 'TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGACGGTCACAGCTTGTCTGTAAGCGGATGCCGGGAGCAGACAAGCCCGTCAGGGCGCGTCAGCGGGTGTTGGCGGGTGTCGGGGCTGGCTTAACTATGCGGCGTTTAAACTTAGCAGATGCGCGCACCTGCGTTGTTACCACAACTCTTATGAGGCCCGCGGACAGCATCAAACTGTAAGATTCCGCCACATTTTATACACTCTGGTCCTTTAACTGGCAAACCTTCGGGCGTAATGCCCAATTTTTCGCCTTTGTCTTTTGCCTTTTTCACTTCACGTGCTTCTGGTACATACTTGCAATTTATACAGTGATGACCGCTGAATTTGTATCTTCCATAGCATCTAGCACATACTCGATTTTTACCACTCCAATCTTTATAAAAATACTTGATTCCCTTTCTGGGACAAGCAACACAGTGTTTTAGATTCTTTTTTTGTGATATTTTAAGCTGTTCTCCCACACAGCAGCCTCGACATGATTTCACTTCTATTTTGTTGCCAAGCAAGAAATTTTTATGGCCTTCTATCGTAAGCCCATATACAGTACTCTCACCCTGGAAATCATCCGTGAAGCTGAAATATACGGGTTCCCTTTTTATAATTGGCGGAACTTCTCTTGTTTTGTGACCACTTCGACAATATGACAAAACATTCTGTGAAGTTGTTCCCCCAGCATCAGAGCAGATTGTACTGAGAGTGCACCGGCGCGCCAGATCTGTTTAGCTTGCCTCGTCCCCGCCGGGTCACCCGGCCAGCGACATGGGGGCCCAGAATACCCTCCTTGACAGTCTTGACGTGCGCAGCTCAGGGGCATGATGTGACTGTCGCCCGTACATTTAGCCCATACATCCCCATGTATAATCATTTGCATCCATACATTTTGATGGCCGCACGGCGCGAAGCAAAAATTACGGCTCCTCGCTGCAGACCTGCGAGCAGGGAAACGCTCCCCTCACAGACGCGTTGAATTGTCCCCACGCCGCGCCCCTGTAGAGAAATATAAAAGGTTAGGATTTGCCACTGAGGTTCTTCTTTCATATACTTCCTTTTAAAATCTTGCTAGGATACAGTTCTCACATCACATCCGAACATAAACAACCATGGGTAAGGAAAAGACTCACGTTTCGAGGCCGCGATTAAATTCCAACATGGATGCTGATTTATATGGGTATAAATGGGCTCGCGATAATGTCGGGCAATCAGGTGCGACAATCTATCGATTGTATGGGAAGCCCGATGCGCCAGAGTTGTTTCTGAAACATGGCAAAGGTAGCGTTGCCAATGATGTTACAGATGAGATGGTCAGACTAAACTGGCTGACGGAATTTATGCCTCTTCCGACCATCAAGCATTTTATCCGTACTCCTGATGATGCATGGTTACTCACCACTGCGATCCCCGGCAAAACAGCATTCCAGATATTAGAAGAATATCCTGATTCAGGTGAAAATATTGTTGATGCGCTGGCAGTGTTCCTGCGCCGGTTGCATTCGATTCCTGTTTGTAATTGTCCTTTTAACAGCGATCGCGTATTTCGTCTCGCTCAGGCGCAATCACGAATGAATAACGGTTTGGTTGATGCGAGTGATTTTGATGACGAGCGTAATGGCTGGCCTGTTGAACAAGTCTGGAAAGAAATGCATAAGCTTTTGCCATTCTCACCGGATTCAGTCGTCACTCATGGTGATTTCTCACTTGATAACCTTATTTTTGACGAGGGGAAATTAATAGGTTGTATTGATGTTGGACGAGTCGGAATCGCAGACCGATACCAGGATCTTGCCATCCTATGGAACTGCCTCGGTGAGTTTTCTCCTTCATTACAGAAACGGCTTTTTCAAAAATATGGTATTGATAATCCTGATATGAATAAATTGCAGTTTCATTTGATGCTCGATGAGTTTTTCTAATCAGTACTGACAATAAAAAGATTCTTGTTTTCAAGAACTTGTCATTTGTATAGTTTTTTTATATTGTAGTTGTTCTATTTTAATCAAATGTTAGCGTGATTTATATTTTTTTTCGCCTCGACATCATCTGCCCAGATGCGAAGTTAAGTGCGCAGAAAGTAATATCATGCGTCAATCGTATGTGAATGCTGGTCGCTATACTGCTGTCGATTCGATACTAACGCCGCCATCCAGTGTCCGCCAGGGTTTTCCCAGTCACGACGCCTCTACCTTGCAGACCCATATAATATAATAACTAAATAAGTAAATAAGACACACGCGAGAACATATATACACAATTACAGTAACAATAACAAGAGGACAGATACTACCAAAATGTGTGGGGAAGCGGGTAAGCTGCCACAGCAATTAATGCACAACATTTAACCTACATTCTTCCTTATCGGATCCTCAAAACCCTTAAAAACATATGCCTCACCCTAACATATTTTCCAATTAACCCTCAATATTTCTCTGTCACCCGGCCTCTATTTTCCATTTTCTTCTTTACCCGCCACGCGTTTTTTTCTTTCAAATTTTTTTCTTCCTTCTTCTTTTTCTTCCACGTCCTCTTGCATAAATAAATAAACCGTTTTGAAACCAAACTCGCCTCTCTCTCTCCTTTTTGAAATATTTTTGGGTTTGTTTGATCCTTTCCTTCCCAATCTCTCTTGTTTAATATATATTCATTTATATCACGCTCTCTTTTTATCTTCCTTTTTTTCCTCTCTCTTGTATTCTTCCTTCCCCTTTCTACTCAAACCAAGAAGAAAAAGAAAAGGTCAATCTTTGTTAAAGAATAGGATCTTCTACTACATCAGCTTTTAGATTTTTCACGCTTACTGCTTTTTTCTTCCCAAGATCGAAAATTTACTGAATTAACAGGGCCCCCCCTCGAGGTCGACGGTATCGATAAGCTTGAAGCAAGCCTCCTGAAAGATGGGTACCCGCCCATATGCTTGCCCTGTCGAGTCCTGCGATCGCCGCTTTTCTCGCCACGCCAATCTTACCCGCCATATCCGCATCCATACCGGTCAGAAGCCCTTCCAGTGTCGAATCTGCATGCGTAACTTCAGTCGTAATGCGAACCTTGTGCGCCACATCCGCACCCACACAGGATCCCAAAAGCCGTTCCAATGTCGGATCTGTATGCGGAACTTTAGTCGAAAGGCCGACCTGAGGCGTCACATTCGCACGCACACCGGCGAGAAGCCTTTTGCCTGTGACATTTGTGGGAGGAAGTTTGCCAGGAAGGGCGACCTCAAGAGGCATACCAAAATCCATACAGGTGGCGGAGGCACACCTGCAGCTGCGTCGACTCTAGAGGATCCATCTGCTGGAGACATGAGAGCTGCCAACCTTTGGCCAAGCCCGCTCATGATCAAACGCTCTAAGAAGAACAGCCTGGCCTTGTCCCTGACGGCCGACCAGATGGTCAGTGCCTTGTTGGATGCTGAGCCCCCCATACTCTATTCCGAGTATGATCCTACCAGACCCTTCAGTGAAGCTTCGATGATGGGCTTACTGACCAACCTGGCAGACAGGGAGCTGGTTCACATGATCAACTGGGCGAAGAGGGTGCCAGGCTTTGTGGATTTGACCCTCCATGATCAGGTCCACCTTCTAGAATGTGCCTGGCTAGAGATCCTGATGATTGGTCTCGTCTGGCGCTCCATGGAGCACCCAGTGAAGCTACTGTTTGCTCCTAACTTGCTCTTGGACAGGAACCAGGGAAAATGTGTAGAGGGCATGGTGGAGATCTTCGACATGCTGCTGGCTACATCATCTCGGTTCCGCATGATGAATCTGCAGGGAGAGGAGTTTGTGTGCCTCAAATCTATTATTTTGCTTAATTCTGGAGTGTACACATTTCTGTCCAGCACCCTGAAGTCTCTGGAAGAGAAGGACCATATCCACCGAGTCCTGGACAAGATCACAGACACTTTGATCCACCTGATGGCCAAGGCAGGCCTGACCCTGCAGCAGCAGCACCAGCGGCTGGCCCAGCTCCTCCTCATCCTCTCCCACATCAGGCACATGAGTAACAAAGGCATGGAGCATCTGTACAGCATGAAGTGCAAGAACGTGGTGCCCCTCTATGACCTGCTGCTGGAGATGCTGGACGCCCACCGCCTACATGCGCCCACTAGCCGTGGAGGGGCATCCGTGGAGGAGACGGACCAAAGCCACTTGGCCACTGCGGGCTCTACTTCATCGG'}}

    assert len(parsed) == 105
    assert parsed[0] == expected_first
