# __version__.py
# autogenerated by keats 0.1.0
__version__ = "1.0.0a3"
__name__ = "pyblastbio"
__title__ = "pyblastbio"
__authors__ = ['First Last <youemail@domain.com>']
__repo__ = None
__homepage__ = "https://www.github.com/jvrana/pyblast"
__description__ = ""
